<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('lessons', function (Blueprint $table) {
            $table->tinyInteger('ai_generated')->default(0)->after('status')
                ->comment('1 if this lesson was generated by AI');
            $table->text('ai_prompt')->nullable()->after('ai_generated')
                ->comment('The topic/prompt the teacher submitted to AI');
        });
    }

    public function down(): void
    {
        Schema::table('lessons', function (Blueprint $table) {
            $table->dropColumn(['ai_generated', 'ai_prompt']);
        });
    }
};
